version: '3.8'
services:
  postgres:
    image: postgres:11
    restart: on-failure
    ports:
      - "5434:5432"
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
volumes:
  postgres_volume: